export const FETCH_COUNTRY_TO_STATE_LOADING = "FETCH_COUNTRY_TO_STATE_LOADING"
export const FETCH_COUNTRY_TO_STATE_SUCCESS = "FETCH_COUNTRY_TO_STATE_SUCCESS"
export const FETCH_COUNTRY_TO_STATE_FAIL = "FETCH_COUNTRY_TO_STATE_FAIL"

export const FETCH_CITY_TO_STATE_LOADING = "FETCH_CITY_TO_STATE_LOADING"
export const FETCH_CITY_TO_STATE_SUCCESS = "FETCH_CITY_TO_STATE_SUCCESS"
export const FETCH_CITY_TO_STATE_FAIL = "FETCH_CITY_TO_STATE_FAIL"


export const FETCH_AIR_DETAIL_TO_STATE_LOADING = "FETCH_AIR_DETAIL_TO_STATE_LOADING"
export const FETCH_AIR_DETAIL_TO_STATE_SUCCESS = "FETCH_AIR_DETAIL_TO_STATE_SUCCESS"
export const FETCH_AIR_DETAIL_TO_STATE_FAIL = "FETCH_AIR_DETAIL_TO_STATE_FAIL"
